### ISSUE TITLE
code understand

### ISSUE THREAD

**Issue by miaolin968** [sherwinbahmani/tc4d#1]
Dear author:
This is a great job, since I don't know much about the 3D field, it is a bit difficult for me to understand your code, which code do I need to focus on in your code?

**Comment by sherwinbahmani** [comment]
Hi,

It depends on what you are interested in. The main file is https://github.com/sherwinbahmani/tc4d/blob/main/threestudio/systems/tc4d.py and everything is controlled through that. I woulf start looking at that file to understand the main concept.

**Comment by sherwinbahmani** [comment]
I will close this issue, please let me know if there is something unclear.
