### ISSUE TITLE
Training stages

### ISSUE THREAD

**Issue by SYZhang0805** [sherwinbahmani/tc4d#3]
What is the difference between the three stages in launch.py? What are the three stages to accomplish? Which part of the paper do these three stages correspond to?

When I was in the first stage of training, I got the following display in the terminal, I couldn't tell how many epochs needed to be trained and how long each epoch needed to be trained.
![image](https://github.com/sherwinbahmani/tc4d/assets/46389660/62a62d81-7b7e-47e1-8dfe-45c5221ee41d)

**Comment by sherwinbahmani** [comment]
Hi,

The three stages follow the multi stage training concept in 4D-fy: https://sherwinbahmani.github.io/4dfy/
Stage 1 is using MVDream, stage 2 MVDream with ProlificDreamer Stable Diffusion. After stage 2 there is the final static object. Stage 3 is the dynamic stage with VideoCrafter2.

Everything only has one epoch, the max number of steps are specified in the configs, e.g., here: https://github.com/sherwinbahmani/tc4d/blob/b419e51c21e7011073cff384cc79c2cc06cc6763/configs/tc4d_stage_1.yaml#L199
E.g., first stage should take around one hour

**Comment by SYZhang0805** [comment]
Thank you very much!

**Comment by sherwinbahmani** [comment]
I guess this issue is solved. Please reopen, if the issue is not solved!
