### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by SYZhang0805** [sherwinbahmani/tc4d#4]
I used a 24GB 3090 to run your code, showing a CUDA out of memory when running to stage 3. I used the config of 24G memory but it is still out of memory. Is there any other way to reduce CUDA  memory?

**Comment by sherwinbahmani** [comment]
Have you checked the README and tried reducing the number of points or frames? This should reduce it until it works on your GPU. I only quickly tested it on 24 GB, since I am using 80GB, but it was training fine on 24 GB.

**Comment by SYZhang0805** [comment]
Thank you. When I set 'low_ram_vae=1', it works. I wonder does this affects the generation quality.

**Comment by sherwinbahmani** [comment]
It will slow down convergence speed for sure, so you have to train longer probably. But you should try it out on the deer example and compare it to the result on the website. You should try to maximize your GPU usage as much as possible. The visual quality should not degrade, maybe the motion can be affected. You can show my your result after it trained for maybe 10k iterations to compare

**Comment by SYZhang0805** [comment]
OK, thank you for your help!

**Comment by sherwinbahmani** [comment]
Please feel free to reopen this issue, if it is not solved!
