### ISSUE TITLE
Why use NeRF?

### ISSUE THREAD

**Issue by yifliu3** [sherwinbahmani/tc4d#5]
Dear devs,

Thanks a lot for your work and I'm inspired a lot. I'm curious about the choice of 3D representation: why use NeRF instead of 3DGS? 
Besides, I find DreamGaussian4D adopts the 3DGS and can train very fast, but it seems that the quality is rather coarse. I'm wondering if this comes from the characteristics of 3DGS or other designs. 

Looking forward to your reply. Thanks a lot!

**Comment by sherwinbahmani** [comment]
Hi,

The main reason is that text-to-3DGS doesn't show high quality yet reliably. So we decided to stick with a high quality pipeline using NeRFs. Of course it would be great to show this with 3DGS for fast training and rendering. Hopefully somebody can make this work soon.

**Comment by sherwinbahmani** [comment]
Feel free to reopen if there are more questions!
