### ISSUE TITLE
No need to save guidance model in the checkpoint

### ISSUE THREAD

**Issue by AlvinYH** [sherwinbahmani/tc4d#7]
It seems that the current version of code saves the guidance model (SD) as part of the checkpoint, resulting in approximately 5GB of memory usage in total. This can be improved.

**Comment by sherwinbahmani** [comment]
Hi,

I think this was some issue in the original threestudio implementation. The reason to save the guidance model is because of the fine-tuning of the LoRA layers in the Stable Diffusion model for VSD. In the third stage, the guidance model shouldn‘t be part of the checkpoint anymore.

**Comment by AlvinYH** [comment]
Hi, @sherwinbahmani. Thanks for your explanation! You're right.
